[timezones]
syd = Australia/Sydney
tyo = Asia/Tokyo
hkt = Asia/Hong_Kong
ist = Asia/Kolkata
par = Europe/Paris
bst = Europe/London
gmt = Etc/GMT
nyk = America/New_York
utc = UTC
sea = America/Los_Angeles

[display]
main_timezone = HKT
refresh_ms = 1000
bg = #3c3c3c
fg = #00ff00

[fonts]
family = Menlo
main_size = 19
table_size = 14
header_size = 11

[transparency]
main_window = 0.5
conversion_table = 0.90

[position]
x = 2073
y = 890

